# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=250)),
                ('resume_file', models.FileField(default='', upload_to='')),
                ('interns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.Internship')),
            ],
        ),
    ]
