# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-17 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='album',
        ),
        migrations.AddField(
            model_name='internship',
            name='company_logo',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
