# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-17 00:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_auto_20180317_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='internship',
            name='Post',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 3, 32, 796774, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='about',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 3, 57, 341366, tzinfo=utc), max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='benefits',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 4, 7, 749924, tzinfo=utc), max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='role',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 4, 17, 566714, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 4, 21, 294130, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='stu',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 4, 27, 366242, tzinfo=utc), max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='time',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 0, 4, 30, 878415, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
