# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_auto_20180317_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company_logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
