# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-17 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_internship_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('user', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='internship',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interns',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.CharField(default=datetime.datetime(2018, 3, 17, 19, 17, 15, 177383, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='stud',
            field=models.CharField(max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='intern',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.Bussiness'),
        ),
    ]
