# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-17 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_auto_20180318_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bussiness',
        ),
    ]
