# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-17 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_auto_20180318_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('writer', models.CharField(max_length=250)),
            ],
        ),
    ]
